# https://github.com/developmentseed/how/issues/149
# ssh-keygen -t rsa -b 4096 -C WorldBank-Transport/rah -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:8

    working_directory: ~/repo

    environment:
      - STAGING_BRANCH: develop
      - PRODUCTION_BRANCH: master
      - GH_REF: git@github.com:WorldBank-Transport/rah.git
      - GH_NAME: "Development Seed"
      - GH_EMAIL: "dev@developmentseed.org"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to Surge
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              cp ./dist/index.html ./dist/200.html
              ./node_modules/surge/lib/cli.js --project ./dist --domain rah.surge.sh
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi
